window.FSTI_ALUMNI = [
 {
  "id": 1,
  "name": "M. AGUS PRIYONO",
  "jabatan": "Kepala Urusan Operator Baller & Case Packer",
  "instansi": "Gudang Garam Gempol",
  "tahunMasuk": "2014",
  "tahunLulus": "2018",
  "testimoni": "Sebagai alumni Program Studi Teknik Informatika Universitas Widya Gama Malang, saya yakin pendidikan yang saya terima menjadi bekal utama dalam menjalani karier. Jadilah yang terbaik tapi tetap jaga sopan santun.",
  "foto": "assets/images/alumni/m-agus-priyono.webp",
  "fotoDrive": "https://drive.google.com/open?id=1eue-GbAKhVCTgYV2rzuNFmU2UGYtG6ZL",
  "email": "shaolinagus@gmail.com",
  "slug": "m-agus-priyono"
 },
 {
  "id": 2,
  "name": "Lionardi Ursaputra Pratama",
  "jabatan": "Pemilik",
  "instansi": "PT Pintu Inovasi Indonesia",
  "tahunMasuk": "2017",
  "tahunLulus": "2024",
  "testimoni": "Selama menempuh studi di Program Studi Teknik Informatika Universitas Widya Gama Malang, Alhamdulillah kualitas materi maupun tenaga pengajar tidak kalah dari universitas ternama meskipun dengan spp yang terjangkau. Saya bangga menjadi alumni UWG.",
  "foto": "assets/images/alumni/lionardi-ursaputra.webp",
  "fotoDrive": "https://drive.google.com/open?id=1EFxFhrevp33w_p4QbQXGZHEsTrvb74vB",
  "email": "app.cordelia@gmail.com",
  "slug": "lionardi-ursaputra-pratama"
 },
 {
  "id": 3,
  "name": "Ismail Akbar",
  "jabatan": "Kepala Unit Pengembangan Sistem dan Teknologi Informasi",
  "instansi": "Universitas Widya Gama",
  "tahunMasuk": "2014",
  "tahunLulus": "2017",
  "testimoni": "Bagi saya, program studi S1 Teknik Informatika Universitas Widya Gama Malang adalah inkubator yang sempurna dalam menyeimbangkan tiga pilar penting karier saya saat ini: sebagai akademisi, praktisi, dan profesional.\n\nSecara akademisi, kurikulum S1 Teknik Informatika Universitas Widya Gama Malang memberikan fondasi teoritis dan logika yang sangat kuat. Hal ini menjadi modal utama yang memudahkan saya menyelesaikan studi S2 Informatika, serta menjadi landasan saya hari ini dalam mentransfer ilmu dan membimbing mahasiswa sebagai dosen.\n\nDari sudut pandang praktisi, ekosistem belajar di S1 Teknik Informatika Universitas Widya Gama Malang mendidik saya untuk adaptif terhadap perkembangan teknologi mutakhir. Pengalaman berbasis proyek selama kuliah membentuk kemampuan problem-solving yang aplikatif, yang kini saya terapkan dalam merancang dan mengeksekusi solusi teknologi di lingkungan kampus.\n\nKini, sebagai profesional yang dipercaya mengemban amanah sebagai Kepala Unit Pengembangan Sistem dan Teknologi Informasi (PSTI) Universitas Widya Gama, saya merasakan betul bagaimana nilai-nilai kepemimpinan, integritas, dan manajerial yang ditanamkan sejak S1 membantu saya memimpin transformasi digital universitas.\n\nS1 Teknik Informatika Universitas Widya Gama Malang tidak hanya mencetak lulusan yang siap kerja, tetapi melahirkan konseptor, eksekutor, dan pemimpin di sektor teknologi.",
  "foto": "assets/images/alumni/ismail-akbar-alumni.webp",
  "fotoDrive": "https://drive.google.com/open?id=1jPzGnhHjoXXuuBXPi9PdXjBL8-IoLx1A",
  "email": "akbar.ismail@unmer.ac.id",
  "slug": "ismail-akbar"
 },
 {
  "id": 4,
  "name": "Dimas Rossiawan Hendra Putra",
  "jabatan": "Dosen Elektronika",
  "instansi": "Politeknik Negeri Malang",
  "tahunMasuk": "2016",
  "tahunLulus": "2018",
  "testimoni": "Menjadi bagian dari keluarga besar Universitas Widyagama Malang merupakan pengalaman yang sangat berharga dalam perjalanan pendidikan saya. Kampus ini tidak hanya membekali saya dengan pengetahuan dan kompetensi akademik, tetapi juga menanamkan nilai-nilai integritas, tanggung jawab, serta semangat untuk terus berkembang dan beradaptasi dengan perubahan.\n\nSuasana belajar yang kondusif, dukungan para dosen yang profesional, serta berbagai kesempatan untuk mengembangkan potensi diri menjadi bekal yang sangat berarti dalam menghadapi dunia kerja dan kehidupan bermasyarakat. Pengalaman selama menempuh pendidikan di Universitas Widyagama Malang telah membentuk pola pikir yang lebih kritis, percaya diri, dan siap menghadapi berbagai tantangan di masa depan.\n\nSebagai alumni, saya merasa bangga pernah menjadi bagian dari Universitas Widyagama Malang. Semoga kampus ini terus meningkatkan kualitas pendidikan, melahirkan lulusan yang unggul, berkarakter, dan mampu memberikan kontribusi positif bagi masyarakat, dunia industri, serta pembangunan bangsa.",
  "foto": "assets/images/alumni/dimas-rossiawan.webp",
  "fotoDrive": "https://drive.google.com/open?id=1PzPm-I3WPTukro7E9kmpudiD7Ch4D_65",
  "email": "dimas.rossi@polinema.ac.id",
  "slug": "dimas-rossiawan-hendra-putra"
 },
 {
  "id": 5,
  "name": "Hesti Sholikah",
  "jabatan": "Analis SDM Aparatur Ahli Pertama",
  "instansi": "Sekretariat Daerah Kab. TTU",
  "tahunMasuk": "2013",
  "tahunLulus": "2017",
  "testimoni": "Saya bangga menjadi alumni Univ Widyagama.\nSemoga kampus ini terus berkembang, berprestasi, dan mencetak lulusan yang unggul serta berintegritas.",
  "foto": "assets/images/alumni/hesti-sholikah.webp",
  "fotoDrive": "https://drive.google.com/open?id=13lV19QVtkOePGtHpx0qdRV0EhQupaeHv",
  "email": "hestisholeha@gmail.com",
  "slug": "hesti-sholikah-skom"
 },
 {
  "id": 6,
  "name": "Ega Yuda Syahputra",
  "jabatan": "Staff",
  "instansi": "Universitas Widya Gama Malang",
  "tahunMasuk": "2021",
  "tahunLulus": "2024",
  "testimoni": "Saya bangga menjadi bagian dari Program Studi Teknik Informatika Universitas Widya Gama Malang. Perkuliahan yang berkualitas, dosen yang kompeten, serta berbagai kesempatan untuk mengembangkan potensi diri menjadi bekal yang sangat berarti bagi perjalanan karier saya. Terima kasih atas semua ilmu, pengalaman, dan dukungan yang telah diberikan. Semoga fakultas ini terus menjadi tempat lahirnya generasi yang unggul dan menginspirasi.",
  "foto": "assets/images/alumni/ega-yuda-syahputra.webp",
  "fotoDrive": "https://drive.google.com/open?id=1GRBxfV-Uv2Fvq52V1FClm5G0JDsVUXD3",
  "email": "yudaega35@gmail.com",
  "slug": "ega-yuda-syahputra"
 },
 {
  "id": 7,
  "name": "RIZKY RATNA PANGGALI",
  "jabatan": "Area Retail Analyst",
  "instansi": "PT HM Sampoerna Tbk",
  "tahunMasuk": "2012",
  "tahunLulus": "2017",
  "testimoni": "Bangga menjadi alumni Program Studi Teknik Informatika Universitas Widya Gama Malang. Selain belajar tentang Teknik Informatika di sini, saya juga belajar organisasi yang bisa melatih public speaking, problem solving, leadership, berkolaborasi, dan saya cukup baik bertumbuh karena lingkungan pendukung yang supportif (termasuk dosen terkait).",
  "foto": "assets/images/alumni/rizky-ratna-panggali.webp",
  "fotoDrive": "https://drive.google.com/open?id=1efE3XWZvbfHdOFFdqTANEcp3vHxlcOA5",
  "email": "rizkyratna23@gmail.com",
  "slug": "rizky-ratna-panggali"
 },
 {
  "id": 8,
  "name": "Wardianto",
  "jabatan": "Dosen",
  "instansi": "Universitas Nurul Huda",
  "tahunMasuk": "2014",
  "tahunLulus": "2018",
  "testimoni": "Menjadi bagian dari universitas Widyagama Malang merupakan salah satu keputusan terbaik dalam perjalanan hidup saya. Tidak hanya memperoleh ilmu pengetahuan yang relevan dengan perkembangan zaman, saya juga dibentuk menjadi pribadi yang memiliki integritas, kemampuan berpikir kritis, serta semangat untuk terus belajar. Lingkungan akademik yang kondusif, dosen yang kompeten, dan berbagai pengalaman organisasi telah menjadi bekal yang sangat berharga dalam menghadapi tantangan di dunia kerja maupun kehidupan bermasyarakat. Saya bangga menjadi alumni universitas Widyagama Malang dan percaya bahwa institusi ini akan terus melahirkan generasi yang unggul, berkarakter, dan mampu memberikan kontribusi nyata bagi bangsa.",
  "foto": "assets/images/alumni/wardianto.webp",
  "fotoDrive": "https://drive.google.com/open?id=1cnb5f6MqE8VjMqk99Gcl6ra1MkHqkm3Y",
  "email": "wardianto06@gmail.com",
  "slug": "wardianto"
 },
 {
  "id": 9,
  "name": "Zahri Aksa Dautd",
  "jabatan": "Web Developer",
  "instansi": "Harvest Solution",
  "tahunMasuk": "2022",
  "tahunLulus": "2026",
  "testimoni": "Selama menempuh studi di Program Studi Teknik Informatika Universitas Widya Gama Malang, saya memperoleh fondasi teknis yang kuat dalam pengembangan web dan sistem informasi. Pengalaman proyek dan bimbingan dosen membantu saya beradaptasi cepat di industri teknologi. Saat ini sebagai Web Developer di Harvest Solution, saya menerapkan ilmu dan keterampilan yang saya dapat selama kuliah untuk membangun solusi digital yang bermanfaat. Saya bangga menjadi alumni UWG dan berharap kampus terus melahirkan talenta teknologi yang unggul.",
  "foto": "assets/images/alumni/zahri-aksa-dautd.webp",
  "fotoDrive": "https://drive.google.com/open?id=1h9dtCp6WqGvtQT1u2oLULAgV_KpMmSoJ",
  "email": "wood25049@gmail.com",
  "slug": "zahri-aksa-dautd"
 },
 {
  "id": 10,
  "name": "Afif Jauhar",
  "jabatan": "Guru",
  "instansi": "SMK Bidayatul Hidayah Mojokerto",
  "tahunMasuk": "2019",
  "tahunLulus": "2025",
  "testimoni": "Sebagai alumni Program Studi Teknik Informatika Universitas Widya Gama Malang, saya merasa sangat terbantu dengan materi yang diberikan. Mantap, menambah wawasan dalam berprogram, dan mengenal yang namanya dataset, logika digital, fitur dalam sebuah program, memahami siklus jaringan, serta belajar untuk mengetahui skill dan kemampuan yang dimiliki. Terima kasih UWG.",
  "foto": "assets/images/alumni/afif-jauhar.webp",
  "fotoDrive": "https://drive.google.com/open?id=1-A8-Et3-JyTyieWeFN7KVXalxSU1cuXf",
  "email": "afifj58@gmail.com",
  "slug": "afif-jauhar"
 },
 {
  "id": 11,
  "name": "Dwi Ahmad Darmawan",
  "jabatan": "Leader EDP (Elektronik Data Processing)",
  "instansi": "PT Inti Cakra Citra (Indogrosir) Malang",
  "tahunMasuk": "2013",
  "tahunLulus": "2017",
  "testimoni": "Testimoni selama di UWG: selama saya kuliah di sana sangat membantu karena ada kelas karyawan, sehingga waktunya lebih fleksibel untuk kita yang sudah bekerja. Walaupun kita bukan kelas reguler, tapi juga mendapat porsi yang sama terkait pembelajaran dengan kelas reguler. Terima kasih atas semua bimbingan dan dukungan dari dosen serta civitas akademika Program Studi Teknik Informatika Universitas Widya Gama Malang.",
  "foto": "assets/images/alumni/dwi-ahmad-darmawan.webp",
  "fotoDrive": "https://drive.google.com/file/d/1w-c18abLmRTnN7tnbBPVEPIXEIPrjKOB/view?usp=drive_link",
  "email": "zepyr027@gmail.com",
  "slug": "dwi-ahmad-darmawan"
 },
 {
  "id": 12,
  "name": "M tri anjasmoro",
  "jabatan": "Produksi",
  "instansi": "PT. Easterntex",
  "tahunMasuk": "2016",
  "tahunLulus": "2020",
  "testimoni": "Terima kasih untuk seluruh dosen dan pihak kampus atas bimbingan, ilmu, dan dukungannya selama menempuh pendidikan. Saya bersyukur dapat menyelesaikan studi dengan baik dan memperoleh banyak ilmu dan pengalaman yang bermanfaat. Semoga Widyagama terus mencetak lulusan yang berdaya saing tinggi.",
  "foto": "assets/images/alumni/m-tri-anjasmoro.webp",
  "fotoDrive": "https://drive.google.com/file/d/1dkU5_xSCHiVerARjaWanZARHWFpGaBOg/view?usp=drive_link",
  "email": "zepyr027@gmail.com",
  "slug": "m-tri-anjasmoro"
 },
 {
  "id": 13,
  "name": "Tri Mukti Lestari",
  "jabatan": "Dosen Program Studi Informatika",
  "instansi": "UIN Maulana Malik Ibrahim Malang",
  "tahunMasuk": "2011",
  "tahunLulus": "2015",
  "testimoni": "Pengalaman akademik dan non-akademik yang saya dapat selama kuliah di Program Studi Teknik Informatika Universitas Widya Gama Malang sangat membentuk kompetensi saya di bidang ilmu komputer. Kurikulum yang adaptif, bimbingan tugas akhir yang intensif, dan budaya riset yang dibangun prodi menjadi fondasi kuat saat saya menempuh S2 dan mengikuti seleksi dosen ASN. Saat ini saya mengabdi sebagai Dosen PNS di Program Studi Informatika, UIN Maulana Malik Ibrahim Malang. Saya bangga menjadi alumni dari Prodi Teknik Informatika Universitas Widya Gama Malang.",
  "foto": "assets/images/alumni/tri-mukti-lestari.webp",
  "fotoDrive": "https://drive.google.com/file/d/1Kc1k82OF0E8en-Fy_UaP1B7woZBe0P7m/view?usp=drive_link",
  "email": "zepyr027@gmail.com",
  "slug": "tri-mukti-lestari"
 },
 {
  "id": 14,
  "name": "Kuncahyo Setyo Nugroho",
  "jabatan": "AI Research Associate & NVIDIA Certified Instructor",
  "instansi": "BINUS University & NVIDIA Deep Learning Institute",
  "tahunMasuk": "2013",
  "tahunLulus": "2019",
  "testimoni": "Saya merasa sangat bersyukur pernah menempuh pendidikan di Program Studi Teknik Informatika Universitas Widya Gama Malang. Selama masa perkuliahan, saya tidak hanya memperoleh bekal pengetahuan dan keterampilan teknis, tetapi juga pengalaman yang membentuk pola pikir, kemampuan dalam menyelesaikan masalah, serta kesiapan untuk menghadapi dunia profesional. Pengalaman tersebut menjadi fondasi yang sangat berarti dalam perjalanan karier saya hingga saat ini.",
  "foto": "assets/images/alumni/kuncahyo-setyo-nugroho.webp",
  "fotoDrive": "https://drive.google.com/file/d/1KGx-24bsANknMemaSdpDWW_DgnLRGpx3/view?usp=sharing",
  "email": "zepyr027@gmail.com",
  "slug": "ir-kuncahyo-setyo-nugroho"
 },
 {
  "id": 15,
  "name": "Dini Kristianti",
  "jabatan": "Kepala Lembaga Penjaminan Mutu",
  "instansi": "Universitas Modern Al Rifa'ie Indonesia",
  "tahunMasuk": "2011",
  "tahunLulus": "2015",
  "testimoni": "Saya bangga menjadi alumni Program Studi Teknik Informatika Universitas Widyagama Malang. Selama menempuh pendidikan, saya memperoleh banyak ilmu, pengalaman, dan wawasan yang sangat bermanfaat, khususnya dalam bidang teknologi informasi dan komputer. Materi yang diberikan tidak hanya memperkuat pemahaman secara teori, tetapi juga membekali saya dengan keterampilan praktis yang dapat diterapkan dalam dunia kerja maupun usaha. Berkat ilmu yang saya peroleh selama kuliah, saya mampu mewujudkan cita-cita menjadi seorang dosen sekaligus mengembangkan usaha sendiri di bidang layanan teknologi, yaitu membuka counter pulsa dan jasa servis komputer. Pengetahuan, kemampuan, serta kepercayaan diri yang saya dapatkan selama kuliah menjadi modal berharga dalam menjalani profesi dan membangun usaha secara mandiri. Saya mengucapkan terima kasih kepada seluruh dosen dan civitas akademika Program Studi Teknik Informatika Universitas Widyagama Malang atas semua bimbingan dan dukungan selama saya menempuh pendidikan.",
  "foto": "assets/images/alumni/dini-kristianti.webp",
  "fotoDrive": "https://drive.google.com/file/d/1x-SiQUp_kL9CyBYztZR14n0zigwq-HGw/view?usp=drive_link",
  "email": "zepyr027@gmail.com",
  "slug": "dini-kristianti"
 }
];

if (typeof lucide !== "undefined" && lucide.createIcons) { setTimeout(() => lucide.createIcons(), 50); }

window.alumniData = window.FSTI_ALUMNI;
